### PR TITLE
Graph uploaded and collaborative document updated

### PR DESCRIPTION
**Pull request by MariaStrv**

### CODE REVIEW

**Comment by DavidFirth** [comment]
Thanks.  Did you forget to add your name to the author list?  or do you prefer it to be omitted?  

David

**Comment by MariaStrv** [comment]
Hi David,

Sorry, completely forgot to add my name... Should I update the collaborative document again?

Thanks!

Kind regards,
Maria

**Comment by DavidFirth** [comment]
Yes, that would be fine.  Please pull the current version, then add your name and commit the
change in your fork of the project, and then send me another pull request.

No worries if you don't get time for it: I can add it myself later.

David

**Comment by MariaStrv** [comment]
Just sent the pull request, all should be in order now, thanks!

Kind regards,
Maria

**Pull request merged**
